name: Regenerate course overview

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  EXPORTFOLDER: 'assets'
  REPOSITORYFOLDER: 'repository'

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          path: repository
          
      - name: Delete and redefine folder for exports
        run: |
          rm -rf ${REPOSITORYFOLDER}/${EXPORTFOLDER}
          mkdir -p ${REPOSITORYFOLDER}/${EXPORTFOLDER}

      - name: Cache repository
        uses: actions/cache@v3
        with:
          path: repository
          key: repository-${{ github.sha }}
      
  commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "Add changes"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
