name: Regenerate course overview

on:
  repository_dispatch:
    types: [new_version]
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  EXPORTFOLDER: 'assets'
  REPOSITORYFOLDER: 'repository'

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repository
        uses: actions/checkout@v3
        with:
          path: repository

      - name: Delete and redefine folder for exports
        run: |
          rm -rf ${REPOSITORYFOLDER}/${EXPORTFOLDER}
          mkdir -p ${REPOSITORYFOLDER}/${EXPORTFOLDER}

      - name: Cache repository
        uses: actions/cache@v3
        with:
          path: repository
          key: repository-${{ github.sha }}

  run_index:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Restore repository
        uses: actions/cache@v3
        with:
          path: repository
          key: repository-${{ github.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          # Removed npm cache that was causing failures

      - name: Install LiaScript exporter
        run: npm install -g @liascript/exporter

      - name: Run exporter for index
        run: |
          cd ${REPOSITORYFOLDER}
          liaex -i index.yml -o index --format project --project-category-blur

  commit:
    needs: 
      [run_index]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Restore repository
        uses: actions/cache@v3
        with:
          path: repository
          key: repository-${{ github.sha }}

      - name:  Commit Changed Files
        run: |
          cd ${REPOSITORYFOLDER}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add new export version of courses" || echo "No changes to commit"
          
      - name: Push Changed Files
        uses: ad-m/github-push-action@master
        with:
          directory: repository
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
